### ISSUE TITLE
NF_About_and_Readme.md

### ISSUE THREAD

**Issue by olafhuerta97** [SystemTruck/SystemTruck#16]
# Update Readme.md file for newcommers

## Description

In the about section we need to give a little explation of what is this project.
The readme.md file is our cover about this project. It explains what this projects is about, may have images, diagrams, tables and clear explanations for the github community what this project is about. It can be held also the roles in this projects and motivations.

## Checklist
- [x] Select asignee(s)
- [x] Select labels (optional)
- [x] Associate to the project

## Include feature
- [x] Create a Branch
- [x] Implement the feature
- [x] Explain how the feature works
- [x] Create a Pull Request 
- [x] Link the Pull request to the issue

**Comment by olafhuerta97** [comment]
@danycmtz could you please open and make a first draft. Contact me for details.

**Comment by danycmtz** [comment]
Already made the first draft and PR, please check it.
