### ISSUE TITLE
NF Update Columns And manage automation

### ISSUE THREAD

**Issue by olafhuerta97** [SystemTruck/SystemTruck#5]
Please create columns  and update the management of automation.

**Comment by olafhuerta97** [comment]
@danycmtz  check this

**Comment by danycmtz** [comment]
I finished this issue, check it please for it to be closed.

**Comment by olafhuerta97** [comment]
Done columns names and automation. @danycmtz  please check

**Comment by olafhuerta97** [comment]
> Done columns names and automation. @danycmtz please check

And if you have no comments please close this issue

**Comment by danycmtz** [comment]
So much better, thank you very much!
